language: python
python:
    - "3.6"
sudo: false
env:
    - DJANGO=1.11
    - DJANGO=master
matrix:
    fast_finish: true
    allow_failures:
      - env: DJANGO=master
install:
    - pip install tox tox-travis
script:
    - tox
