# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 06:00
from __future__ import unicode_literals

from django.db import migrations


def null_zeros(apps, schema_editor):
    Point = apps.get_model('fitness', 'Point')
    for point in Point.objects.all():
        if point.heart_rate == 0:
            point.heart_rate = None
        if point.cadence == 0:
            point.cadence = None
        point.save()


def zero_nulls(apps, schema_editor):
    Point = apps.get_model('fitness', 'Point')
    for point in Point.objects.all():
        if point.heart_rate is None:
            point.heart_rate = 0
        if point.cadence is None:
            point.cadence = 0
        point.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20170610_0658'),
    ]

    operations = [
        migrations.RunPython(null_zeros, reverse_code=zero_nulls, elidable=True),
    ]
