# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20170610_0700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='point',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='point',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lap',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='fitness.Activity'),
        ),
        migrations.AlterField(
            model_name='point',
            name='lap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='fitness.Lap'),
        ),
    ]
