# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 15:06
from __future__ import unicode_literals

from django.db import migrations


def create_themes(apps, unused):
    Theme = apps.get_model('fitness', 'Theme')
    for name, dark in (
            ('cerulean', False),
            ('cosmo', False),
            ('cyborg', True),
            ('darkly', True),
            ('flatly', False),
            ('journal', False),
            ('lumen', False),
            ('paper', False),
            ('readable', False),
            ('sandstone', False),
            ('simplex', False),
            ('slate', True),
            ('solar', True),
            ('spacelab', False),
            ('superhero', True),
            ('united', False),
            ('yeti', False),
    ):
        Theme.objects.update_or_create(name=name, dark=dark)


def create_profiles_for_existing_users(apps, unused):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('fitness', 'Profile')
    Theme = apps.get_model('fitness', 'Theme')
    first_theme = Theme.objects.first()
    for instance in User.objects.all():
        if hasattr(instance, 'profile'):
            continue
        profile = Profile.objects.create(user=instance, theme=first_theme)
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_themes),
        migrations.RunPython(create_profiles_for_existing_users),
    ]
