# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:46
from __future__ import unicode_literals

from django.db import migrations, models


def elevation_gain(points):
    gain = 0
    last_elevation = None
    points_up = 0
    for point in points:
        if last_elevation is not None and point.altitude > last_elevation:
            if points_up < 2:
                points_up += 1
            else:
                gain += (int(point.altitude) - int(last_elevation))
        else:
            points_up = 0
        last_elevation = point.altitude
    return gain


def populate(apps, scheme_editor):
    Activity = apps.get_model('fitness', 'Activity')
    Point = apps.get_model('fitness', 'Point')
    for activity in Activity.objects.all():
        ordered_points = Point.objects.filter(lap__activity=activity).order_by('time')
        activity.distance = ordered_points.last().distance
        activity.duration = (ordered_points.last().time - ordered_points.first().time).total_seconds()
        activity.elevation = elevation_gain(ordered_points)
        activity.data_points = ordered_points.count()
        activity.save()


def blank(apps, scheme_editor):
    Activity = apps.get_model('fitness', 'Activity')
    for activity in Activity.objects.all():
        activity.distance = None
        activity.duration = None
        activity.elevation = None
        activity.data_points = None
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20170623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='elevation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='data_points',
            field=models.IntegerField(null=True),
        ),
        migrations.RunPython(
            populate, reverse_code=blank),
    ]
