# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 18:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


def populate(apps, scheme_editor):
    Activity = apps.get_model('fitness', 'Activity')
    Point = apps.get_model('fitness', 'Point')
    for activity in Activity.objects.all():
        ordered_points = Point.objects.filter(lap__activity=activity).order_by('time')
        activity.stream = {
            a.time.isoformat(): {
                'time': a.time,
                'latitude': a.latitude,
                'longitude': a.longitude,
                'altitude': a.altitude,
                'heart_rate': a.heart_rate,
                'cadence': a.cadence,
                'distance': a.distance,
                'speed': a.speed,
            } for a in ordered_points
        }
        activity.save()


def blank(apps, scheme_editor):
    Activity = apps.get_model('fitness', 'Activity')
    for activity in Activity.objects.all():
        activity.stream = None
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_activity_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stream',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
        migrations.RunPython(
            populate, reverse_code=blank
        ),
    ]
