# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_auto_20170623_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maximum_heart_rate',
            field=models.IntegerField(default=190),
        ),
        migrations.AddField(
            model_name='profile',
            name='minimum_heart_rate',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='activity',
            name='trimp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
