# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_activity_stream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='point',
            name='lap',
        ),
        migrations.DeleteModel(
            name='Lap',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
    ]
